### ISSUE TITLE
部署不成功哇

### ISSUE THREAD

**Issue by sa-da-sa-da** [longern/python-executor#1]
报错信息：
{
    "errorMessage": "Expecting value: line 1 column 1 (char 0)",
    "errorType": "JSONDecodeError",
    "stackTrace": [
        [
            "File \"/code/index.py\"",
            "line 65",
            "in handler",
            "request_obj: dict = json.loads(request_body)"
        ],
        [
            "File \"/usr/local/lib/python3.6/json/__init__.py\"",
            "line 354",
            "in loads",
            "return _default_decoder.decode(s)"
        ],
        [
            "File \"/usr/local/lib/python3.6/json/decoder.py\"",
            "line 339",
            "in decode",
            "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"
        ],
        [
            "File \"/usr/local/lib/python3.6/json/decoder.py\"",
            "line 357",
            "in raw_decode",
            "raise JSONDecodeError(\"Expecting value\", s, err.value) from None"
        ]
    ]
}

**Comment by longern** [comment]
得POST一个JSON请求，格式是{source:<你的代码>}

**Comment by sa-da-sa-da** [comment]
这是来自QQ邮箱的自动回复邮件。感谢您在百忙之中来信！我将会尽快给您回复。
如遇紧急情况，请拨打电话！
